name: build-arch


on:
  push:
    branches:
      - master
  schedule:
    # nightly build
    - cron: "30 */6 * * *"

jobs:
  build-linux:
    timeout-minutes: 1000
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build -t tmp .


#     # - uses: actions/upload-artifact@v2
#       # with:
#         # name: artifacts-linux
#         # path: graphql-engine/server/graphql-engine

