name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run:  docker build -t tmp .

